matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - config/spellcheck/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'lab*/*.md'
  - '*.md'
  - 'docs/**/*.md'
  - 'lab_6_pipeline/universal_dependencies/*.md'
  - 'core_utils/**/*.md'
  default_encoding: utf-8
